version: "3"

services:
  alexmarchant-client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - "./client:/usr/src/app"
      - "/usr/src/app/node_modules"

  alexmarchant-sandbox:
    build: ./sandbox
    ports:
      - "3002:3002"
    volumes:
      - "./sandbox:/usr/src/app"
      - "/usr/src/app/node_modules"