version: "3"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - "./client:/usr/src/app"
      - "/usr/src/app/node_modules"
    depends_on:
      - server
    stdin_open: true
    tty: true
##################################################################
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - "./server:/usr/src/app"
      - "/usr/src/app/node_modules"
    stdin_open: true
    tty: true
