version: "3"

services:
  alexmarchant-client:
    image: alexmarchant/alexmarchant-client
    build: ./client
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - "./client:/usr/src/app"
      - "/usr/src/app/node_modules"

  alexmarchant-sandbox:
    image: alexmarchant/alexmarchant-sandbox
    build: ./sandbox
    command: npm start
    ports:
      - "3002:3002"
    volumes:
      - "./sandbox:/usr/src/app"
      - "/usr/src/app/node_modules"