version: "3"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - "./client:/usr/src/app"
      - "/usr/src/app/node_modules"
    networks:
      - internet

  proxy:
    build: ./proxy
    ports:
      - "3001:80"
    networks:
      - internet
      - no-internet

  sandbox:
    build: ./sandbox
    ports:
      - "3002:3002"
    volumes:
      - "./sandbox:/usr/src/app"
      - "/usr/src/app/node_modules"
    networks:
      - no-internet
    read_only: true

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge