---
- name: Add up to date php release ppa
  apt_repository:
    repo: "ppa:ondrej/php"

- name: Install packages
  apt: 
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - git
    - curl
    - nginx
    - php7.2-cli
    - php7.2-fpm
    - php7.2-pgsql
    - php-imagick
    - php7.2-mbstring
    - php7.2-json
    - php7.2-curl
    - php7.2-zip
    - php7.2-intl
    - php7.2-xml

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Create site root
  file: 
    path: "{{ site_root }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    state: directory
    mode: "2755"

- name: Allow web_user to control php-fpm service
  template:
    src: ../templates/sudoers-web-services.j2
    dest: "/etc/sudoers.d/{{ web_user }}-services"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"

- name: Configure php
  template: 
    src: ../templates/php.ini.j2
    dest: /etc/php/7.2/fpm/php.ini
  notify: restart php7.2-fpm

- name: Configure php-fpm
  template: 
    src: ../templates/php-fpm-poold-www.conf.j2
    dest: /etc/php/7.2/fpm/pool.d/www.conf
  notify: restart php7.2-fpm

- name: Create SSL directory
  file:
    mode: 0700
    path: /etc/nginx/ssl
    state: directory

- name: Generate strong unique Diffie-Hellman group.
  command: openssl dhparam -out dhparams.pem 2048
  args:
    chdir: /etc/nginx/ssl
    creates: /etc/nginx/ssl/dhparams.pem
  notify: restart nginx

- name: Configure nginx
  template: 
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx

