version: 2.1
orbs:
  doctl-orb: digitalocean/cli@0.1.1
  kube-orb: circleci/kubernetes@0.10.0
jobs:
  build:
    machine: true
    steps:
      # checkout git
      - checkout
      # install kubectl
      - kube-orb/install-kubectl
      # install doctl
      - doctl-orb/install
      - doctl-orb/initialize:
          digitalocean-access-token: <<parameters.digitalocean-access-token>>

      # login with credentials stored in the UI
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # pull existing images (cache layers)
      - run: docker pull alexmarchant/alexmarchant-client
      - run: docker pull alexmarchant/alexmarchant-sandbox

      # build the application images
      - run: cd client && docker build -t alexmarchant/alexmarchant-client .
      - run: cd sandbox && docker build -t alexmarchant/alexmarchant-sandbox .

      # deploy the images
      - run: docker push alexmarchant/alexmarchant-client
      - run: docker push alexmarchant/alexmarchant-sandbox

      # install kubeconfig using doctl
      - run: doctl kubernetes cluster kubeconfig save personal-cluster

      # tell kubernetes to pull latest image
      - run: |
          kubectl rollout restart deployment/alexmarchant-client
          kubectl rollout restart deployment/alexmarchant-sandbox