version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      # login with credentials stored in the UI
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application images
      - run: cd client && docker build -t alexmarchant/alexmarchant-client .
      - run: cd sandbox && docker build -t alexmarchant/alexmarchant-sandbox .

      # deploy the images
      - run: docker push alexmarchant/alexmarchant-client
      - run: docker push alexmarchant/alexmarchant-sandbox

      # install kubectl
      - run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl

      # auth kubernetes
      - run: snap install doctl && snap connect doctl:kube-config
      - run: doctl auth init --access-token $DO_ACCESS_TOKEN
      - run: doctl kubernetes cluster kubeconfig save personal-cluster

      # tell kubernetes to pull latest image
      - run: |
          kubectl rollout restart deployment/alexmarchant-client
          kubectl rollout restart deployment/alexmarchant-sandbox