---
- include: tasks/ansible-setup.yml
- include: tasks/prerequisites.yml

- name: Setup Craft server
  hosts: "{{ env }}"
  become: true
  roles:
    - { role: users, tags: [users] }
    - { role: certbot, tags: [certbot] }
    - { role: php-server, tags: [php-server] }
    - { role: postgres, tags: [postgres] }
    - { role: node, tags: [node] }

