---
- name: Initialize the deploy root and gather facts
  deploy_helper:
    path: "{{ site_root }}"

- name: Clone the project to the new release folder
  become: false
  git:
    repo: "{{ git_repo }}"
    dest: "{{ deploy_helper.new_release_path }}"
    accept_hostkey: true

- name: Add an unfinished file, to allow cleanup on successful finalize
  file:
    path: "{{ deploy_helper.new_release_path }}/{{ deploy_helper.unfinished_filename }}"
    state: touch

- name: Install composer packages
  composer:
    command: install
    working_dir: "{{ deploy_helper.new_release_path }}/{{ repo_subtree_path }}"

- name: Set environment variables
  template: 
    src: ../templates/env.j2
    dest: "{{ deploy_helper.new_release_path }}/{{ repo_subtree_path }}/.env"

- name: Install node packages
  shell: npm install
  args:
    chdir: "{{ deploy_helper.new_release_path }}/{{ repo_subtree_path }}"

- name: Build assets
  shell: npm run build
  args:
    chdir: "{{ deploy_helper.new_release_path }}/{{ repo_subtree_path }}"

- name: Ensure shared sources are present
  file:
    path: "{{ deploy_helper.shared_path }}/{{ item.src }}"
    state: directory
    mode: 0755
  with_items: "{{ shared_folders }}"

- name: Ensure shared paths are absent
  file:
    path: "{{ deploy_helper.new_release_path }}/{{ item.path }}"
    state: absent
  with_items: "{{ shared_folders }}"

- name: Create shared symlinks
  file:
    path: "{{ deploy_helper.new_release_path }}/{{ item.path }}"
    src: "{{ deploy_helper.shared_path }}/{{ item.src }}"
    state: link
  with_items: "{{ shared_folders }}"

- name: Finalize the deploy, removing the unfinished file and switching the symlink
  deploy_helper:
    path: "{{ site_root }}"
    release: "{{ deploy_helper.new_release }}"
    state: finalize

- name: Reload php-fpm
  shell: sudo service php7.2-fpm reload
  args:
    chdir: "{{ deploy_helper.new_release_path }}"
    warn: false

