---
- name: Install packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: Create db
  become_user: postgres
  postgresql_db: 
    name: "{{ db_name }}"
    encoding: UTF-8

- name: Create db roles
  become_user: postgres
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: ALL
    role_attr_flags: NOCREATEDB,NOSUPERUSER
